### ISSUE TITLE
More config errors

### ISSUE THREAD

**Issue by dakotabenjamin** [edgarriba/OpenDroneMap#9]
On a fresh machine, I cloned the repo and ran ./configure.sh. It failed, so I went into SuperBuild/build, deleted everythin and ran `cmake .. && make -j 32 > build.log 2>&1`

Check the [gist](https://gist.github.com/dakotabenjamin/3919eac091c941c380ad)

It seems like pcl finished, but I can't really navigate around this new system.

**Comment by dakotabenjamin** [comment]
I thin kthe specific error might be here:

```
CMake Error at /home/dmb2/odm_cmake/SuperBuild/build/catkin/stamp/download-catkin.cmake:9 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/dmb2/odm_cmake/SuperBuild/download/indigo-devel.zip]
      expected hash: [3878179d2a4e7f4273e09bd49e3d48bc]
        actual hash: [86cdc10ec4800a4afa39fe32ffdb0f80]



make[2]: *** [catkin/stamp/catkin-download] Error 1
make[1]: *** [CMakeFiles/catkin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by dakotabenjamin** [comment]
Aside: https://gist.github.com/dakotabenjamin/3919eac091c941c380ad#file-build-log-L1686
`-- Disabled: gpu nonfree ocl stitching superres ts videostab world`

nonfree and stitching need to be enabled

**Comment by edgarriba** [comment]
still having this issue?

**Comment by dakotabenjamin** [comment]
Yes, I haven't tried to install since the issue came up.

**Comment by edgarriba** [comment]
ok, now should be fixed.

**Comment by dakotabenjamin** [comment]
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
jhead is already the newest version.
liblas-bin is already the newest version.
python-pyexiv2 is already the newest version.
python-scipy is already the newest version.
The following packages were automatically installed and are no longer required:
  acl at-spi2-core colord libatk-bridge2.0-0 libatspi2.0-0 libcanberra-gtk3-0
  libcanberra-gtk3-module libcanberra0 libcolord1 libcolorhug1 libexif12
  libgd3 libgphoto2-6 libgphoto2-l10n libgphoto2-port10 libgtk-3-0
  libgtk-3-bin libgtk-3-common libgudev-1.0-0 libgusb2 libieee1284-3
  libnotify-bin libnotify4 libsane libsane-common libtdb1 libvorbisfile3
  libwayland-client0 libwayland-cursor0 libxfont1 libxkbcommon0 libxkbfile1
  notification-daemon sound-theme-freedesktop x11-xkb-utils xfonts-base
  xfonts-encodings xfonts-utils xserver-common xserver-xorg-core
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
-- SuperBuild files will be downloaded to: /home/vagrant/odm/SuperBuild/download
-- SuperBuild source files will be extracted to: /home/vagrant/odm/SuperBuild/src
-- SuperBuild source files will be installed to: /home/vagrant/odm/SuperBuild/install
-- SuperBuild binary files will be located to: /home/vagrant/odm/SuperBuild/build
-- OpenCV 2.4.11 not found --- Adding internal version
-- PCL 1.7.2 not found --- Adding internal version
-- Ceres 1.10.0 not found --- Adding internal version
CMake Error at /usr/share/cmake-2.8/Modules/ExternalProject.cmake:1580 (get_property):
  get_property could not find TARGET gflags.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/ExternalProject.cmake:1808 (_ep_add_configure_command)
  cmake/External-Ceres.cmake:4 (ExternalProject_Add)
  cmake/ExternalProject-Setup.cmake:15 (include)
  CMakeLists.txt:79 (SETUP_EXTERNAL_PROJECT)


-- GFlags 2.1.2 not found --- Adding internal version
-- OpenGV force build --- Adding internal version
-- OpenSfM force build --- Adding internal version
-- CMVS force build --- Adding internal version
-- Catkin force build --- Adding internal version
-- Ecto force build --- Adding internal version
-- LAStools force build --- Adding internal version
-- Configuring incomplete, errors occurred!
See also "/home/vagrant/odm/SuperBuild/build/CMakeFiles/CMakeOutput.log".
Script finished
```

**Comment by dakotabenjamin** [comment]
I think it finished, though, right? despite the error.

**Comment by dakotabenjamin** [comment]
Tried running it but couldn't import ecto. tried setting the python path, but turns out ecto hadn't been built.

**Comment by edgarriba** [comment]
Don't think so. The error comes from the fact that gflags target is created after Ceres target which has gflags as a dependency. Only need to create gflags target before Ceres in CMakelists.txt. I'll fix it tomorrow.

**Comment by dakotabenjamin** [comment]
Looks like a quick fix! I moved it up, it looks like it is working. I'll submit a PR if it finishes successfully

**Comment by dakotabenjamin** [comment]
That part worked, but I'm still unable to make ceres. The error is enigmatic:

```
-- Installing: /home/vagrant/odm/SuperBuild/install/include/ceres/internal/fixed_array.h
-- Installing: /home/vagrant/odm/SuperBuild/install/include/ceres/internal/disable_warnings.h
-- Installing: /home/vagrant/odm/SuperBuild/install/include/ceres/internal/config.h
-- Installing: /home/vagrant/odm/SuperBuild/install/share/Ceres/CeresTargets.cmake
-- Installing: /home/vagrant/odm/SuperBuild/install/share/Ceres/CeresTargets-release.cmake
-- Installing: /home/vagrant/odm/SuperBuild/install/share/Ceres/CeresConfig.cmake
-- Installing: /home/vagrant/odm/SuperBuild/install/share/Ceres/CeresConfigVersion.cmake
-- Installing: /home/vagrant/odm/SuperBuild/install/share/Ceres/FindEigen.cmake
-- Installing: /home/vagrant/odm/SuperBuild/install/share/Ceres/FindGlog.cmake
-- Installing: /home/vagrant/odm/SuperBuild/install/lib/libceres.a
[ 72%] Completed 'ceres'
[ 72%] Built target ceres
make: *** [all] Error 2
Script finished
```

from CMakeError.log

```
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/make "cmTryCompileExec3169035159/fast"
make[3]: Entering directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTryCompileExec3169035159.dir/build.make CMakeFiles/cmTryCompileExec3169035159.d
make[4]: Entering directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp/CMakeFil
Building C object CMakeFiles/cmTryCompileExec3169035159.dir/CheckSymbolExists.c.o
/usr/bin/cc   -fPIC    -o CMakeFiles/cmTryCompileExec3169035159.dir/CheckSymbolExists.c.o   -c /home/vagrant/
ild/build/ceres/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTryCompileExec3169035159
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec3169035159.dir/link.txt --verbose=1
/usr/bin/cc  -fPIC     CMakeFiles/cmTryCompileExec3169035159.dir/CheckSymbolExists.c.o  -o cmTryCompileExec31
dynamic
CMakeFiles/cmTryCompileExec3169035159.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make[4]: Leaving directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
make[4]: *** [cmTryCompileExec3169035159] Error 1
make[3]: Leaving directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
make[3]: *** [cmTryCompileExec3169035159/fast] Error 2

File /home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/make "cmTryCompileExec1386438786/fast"
make[3]: Entering directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTryCompileExec1386438786.dir/build.make CMakeFiles/cmTryCompileExec1386438786.d
make[4]: Entering directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp/CMakeFil
Building C object CMakeFiles/cmTryCompileExec1386438786.dir/CheckFunctionExists.c.o
/usr/bin/cc   -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTryCompileExec1386438786.dir/Che
xists.c.o   -c /usr/share/cmake-2.8/Modules/CheckFunctionExists.c
Linking C executable cmTryCompileExec1386438786
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec1386438786.dir/link.txt --verbose=1
/usr/bin/cc  -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTryCompileExec1386438786.dir/CheckF
ts.c.o  -o cmTryCompileExec1386438786 -rdynamic -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[4]: Leaving directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
make[4]: *** [cmTryCompileExec1386438786] Error 1
make[3]: Leaving directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
make[3]: *** [cmTryCompileExec1386438786/fast] Error 2


Determining if the include file unordered_map exists failed with the following output:
Change Dir: /home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/make "cmTryCompileExec3050822260/fast"
make[3]: Entering directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTryCompileExec3050822260.dir/build.make CMakeFiles/cmTryCompileExec3050822260.d
make[4]: Entering directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp/CMakeFil
Building CXX object CMakeFiles/cmTryCompileExec3050822260.dir/CheckIncludeFile.cxx.o
/usr/bin/c++    -fPIC -fopenmp    -o CMakeFiles/cmTryCompileExec3050822260.dir/CheckIncludeFile.cxx.o -c /hom
dm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp/CheckIncludeFile.cxx
In file included from /usr/include/c++/4.8/unordered_map:35:0,
                 from /home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp/CheckIncludeFile.cxx:1:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support
O C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=
piler options.
 #error This file requires compiler and library support for the \
  ^
make[4]: *** [CMakeFiles/cmTryCompileExec3050822260.dir/CheckIncludeFile.cxx.o] Error 1
make[4]: Leaving directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
make[3]: Leaving directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
make[3]: *** [cmTryCompileExec3050822260/fast] Error 2


Performing C++ SOURCE FILE Test HAVE_SHARED_PTR_IN_STD_NAMESPACE failed with the following output:
Change Dir: /home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/make "cmTryCompileExec4030429808/fast"
make[3]: Entering directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTryCompileExec4030429808.dir/build.make CMakeFiles/cmTryCompileExec4030429808.d
make[4]: Entering directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp/CMakeFil
Building CXX object CMakeFiles/cmTryCompileExec4030429808.dir/src.cxx.o
/usr/bin/c++    -fPIC -fopenmp -DHAVE_SHARED_PTR_IN_STD_NAMESPACE   -o CMakeFiles/cmTryCompileExec4030429808.
.o -c /home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp/src.cxx
/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp/src.cxx: In function ‘int main()’:
/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp/src.cxx:3:34: error: ‘shared_ptr’ is not a membe
                                  std::shared_ptr<int> int_ptr;
                                  ^
/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp/src.cxx:3:50: error: expected primary-expression
t’
                                  std::shared_ptr<int> int_ptr;
                                                  ^
/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp/src.cxx:3:50: error: expected ‘;’ before ‘int’
make[4]: Leaving directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
make[4]: *** [CMakeFiles/cmTryCompileExec4030429808.dir/src.cxx.o] Error 1
make[3]: Leaving directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
make[3]: *** [cmTryCompileExec4030429808/fast] Error 2

Source file was:
#include <memory>
                               int main() {
                                 std::shared_ptr<int> int_ptr;
                                 return 0;
                               }
Performing C++ SOURCE FILE Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE failed with the following output:
Change Dir: /home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/make "cmTryCompileExec2926189506/fast"
make[3]: Entering directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTryCompileExec2926189506.dir/build.make CMakeFiles/cmTryCompileExec2926189506.d
make[4]: Entering directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp/CMakeFil
Building CXX object CMakeFiles/cmTryCompileExec2926189506.dir/src.cxx.o
/usr/bin/c++    -fPIC -fopenmp -DHAVE_SHARED_PTR_IN_TR1_NAMESPACE   -o CMakeFiles/cmTryCompileExec2926189506.
.o -c /home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp/src.cxx
/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp/src.cxx: In function ‘int main()’:
/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp/src.cxx:3:41: error: ‘std::tr1’ has not been dec
                                    std::tr1::shared_ptr<int> int_ptr;
                                         ^
/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp/src.cxx:3:57: error: expected primary-expression
t’
                                    std::tr1::shared_ptr<int> int_ptr;
                                                         ^
/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp/src.cxx:3:57: error: expected ‘;’ before ‘int’
make[4]: Leaving directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
make[4]: *** [CMakeFiles/cmTryCompileExec2926189506.dir/src.cxx.o] Error 1
make[3]: Leaving directory `/home/vagrant/odm/SuperBuild/build/ceres/CMakeFiles/CMakeTmp'
make[3]: *** [cmTryCompileExec2926189506/fast] Error 2

Source file was:
#include <memory>
                                 int main() {
                                   std::tr1::shared_ptr<int> int_ptr;
                                   return 0;
                                 }
```

**Comment by edgarriba** [comment]
what OS and architecture do you have?

**Comment by dakotabenjamin** [comment]
Ubuntu 14.04

**Comment by edgarriba** [comment]
Cannot reproduce your error, for me it's working. Are you using a fresh workspace?

**Comment by edgarriba** [comment]
not sure if this will fix your issue 6459763f7bf9ff7c9d2d82f95918013c4e5911c7

**Comment by dakotabenjamin** [comment]
No, it doesn't. Posting a gist of the configure.sh log [here](https://gist.github.com/dakotabenjamin/bc393709f1f1a4099127)

E: I ran this on a fresh vagrant box, 64-bit Ubuntu 14.04

**Comment by edgarriba** [comment]
Could you build the superbuild with make -j1 only for debug ? In the top of your gist there's an error with the hash of cmvs. Maybe it's that.

**Comment by dakotabenjamin** [comment]
```
Scanning dependencies of target opensfm
[ 81%] Creating directories for 'opensfm'
[ 82%] Performing download step (download, verify and extract) for 'opensfm'
-- downloading...
     src='https://github.com/mapillary/OpenSfM/archive/odm-2.zip'
     dst='/home/vagrant/odm/SuperBuild/download/odm-2.zip'
     timeout='none'
-- downloading... done
-- verifying file...
     file='/home/vagrant/odm/SuperBuild/download/odm-2.zip'
-- verifying file... done
-- extracting...
     src='/home/vagrant/odm/SuperBuild/download/odm-2.zip'
     dst='/home/vagrant/odm/SuperBuild/src/opensfm'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 83%] No patch step for 'opensfm'
[ 85%] No update step for 'opensfm'
[ 86%] Performing configure step for 'opensfm'
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- A library with BLAS API found.
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- A library with BLAS API found.
-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
-- Found AMD header in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
-- Found CAMD header in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
-- Found COLAMD header in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
-- Found CCOLAMD header in: /usr/include/suitesparse
-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
-- Found CHOLMOD header in: /usr/include/suitesparse
-- Found SuiteSparseQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
-- Found SuiteSparseQR header in: /usr/include/suitesparse
-- Found Intel Thread Building Blocks (TBB) library: /usr/lib/libtbb.so, assuming SuiteSparseQR was compiled with TBB.
-- Found Intel Thread Building Blocks (TBB) Malloc library: /usr/lib/libtbbmalloc.so
-- Found SuiteSparse_config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.a
-- Found SuiteSparse_config header in: /usr/include/suitesparse
-- Adding librt: /usr/lib/x86_64-linux-gnu/librt.so to SuiteSparse_config libraries (required on Linux & Unix [not OSX]
if SuiteSparse is compiled with timing).
-- Did not find METIS library (optional SuiteSparse dependency)
-- Found SuiteSparse: TRUE (found version "4.2.1")
-- Found Eigen: /usr/include/eigen3 (found version "3.2.0")
-- Found ceres: /home/vagrant/odm/SuperBuild/install/lib/libceres.a
-- Found Gflags: /usr/include
-- Found Glog: /usr/include
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   python
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.6")
-- Found PythonInterp: /usr/bin/python (found version "2.7.6")
-- Found NumPy: version "1.8.2" /usr/lib/python2.7/dist-packages/numpy/core/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vagrant/odm/SuperBuild/build/opensfm
[ 87%] Performing build step for 'opensfm'
Scanning dependencies of target akaze
[  2%] Building CXX object CMakeFiles/akaze.dir/third_party/akaze/lib/AKAZE.cpp.o
[  5%] Building CXX object CMakeFiles/akaze.dir/third_party/akaze/lib/fed.cpp.o
[  7%] Building CXX object CMakeFiles/akaze.dir/third_party/akaze/lib/nldiffusion_functions.cpp.o
[ 10%] Building CXX object CMakeFiles/akaze.dir/third_party/akaze/lib/utils.cpp.o
Linking CXX static library libakaze.a
[ 10%] Built target akaze
Scanning dependencies of target vl
[ 12%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/svm.c.o
[ 15%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/mathop.c.o
[ 17%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/generic.c.o
[ 20%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/pgm.c.o
[ 23%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/svmdataset.c.o
[ 25%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/homkermap.c.o
[ 28%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/host.c.o
[ 30%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/slic.c.o
[ 33%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/rodrigues.c.o
[ 35%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/covdet.c.o
[ 38%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/imopv_sse2.c.o
[ 41%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/mathop_sse2.c.o
[ 43%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/kmeans.c.o
[ 46%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/fisher.c.o
[ 48%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/lbp.c.o
[ 51%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/aib.c.o
[ 53%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/hog.c.o
[ 56%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/quickshift.c.o
[ 58%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/mathop_avx.c.o
[ 61%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/scalespace.c.o
[ 64%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/vlad.c.o
[ 66%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/dsift.c.o
[ 69%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/liop.c.o
[ 71%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/mser.c.o
[ 74%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/ikmeans.c.o
[ 76%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/getopt_long.c.o
[ 79%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/random.c.o
[ 82%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/stringop.c.o
[ 84%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/sift.c.o
[ 87%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/array.c.o
[ 89%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/imopv.c.o
[ 92%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/hikmeans.c.o
[ 94%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/kdtree.c.o
[ 97%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/gmm.c.o
Linking C static library libvl.a
[ 97%] Built target vl
Scanning dependencies of target csfm
[100%] Building CXX object CMakeFiles/csfm.dir/csfm.cc.o
Linking CXX shared library /home/vagrant/odm/SuperBuild/src/opensfm/opensfm/csfm.so
[100%] Built target csfm
[ 88%] No install step for 'opensfm'
[ 90%] Completed 'opensfm'
[ 90%] Built target opensfm
[100%] Built target pcl
Script finished
```

**Comment by edgarriba** [comment]
nice! what did you do?

**Comment by dakotabenjamin** [comment]
Pulled the most recent commits and changed the cmake call as you suggested.

On that note, the export call to set the `$PYTHONPATH` does not set it globally unless I source the configure script. 

So I set the python path manually to `:/home/vagrant/odm/SuperBuild/install/lib/python2.7/dist-packages` and tried run.py, but I got the following: 

```
vagrant@vagrant-ubuntu-trusty-64:~/odm$ python run.py -h
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    import ecto
  File "/home/vagrant/odm/SuperBuild/install/lib/python2.7/dist-packages/ecto/__init__.py", line 30, in <module>
    from ecto.ecto_main import _cell_base, _cell_cpp, __getitem_list__, __getitem_slice__, __getitem_str__, __getitem_tu
ple__, lookup
ImportError: libecto.so.0.6: cannot open shared object file: No such file or directory
```

libecto.so.0.6 is found in SuperBuild/install/lib

**Comment by edgarriba** [comment]
we need to add SuperBuild/lib to the LD_LIBRARY_PATH.

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/vagrant/odm/SuperBuild/install/lib
```

in the documentation we have to specify that the user must add the SuperBuild path to the PYTHONPATH and LD_LIBRARY_PATH

**Comment by dakotabenjamin** [comment]
Ok. I think that is acceptable.

**Comment by dakotabenjamin** [comment]
Well the config problems are resolved and I'm running a test set right now. Thanks for the help with this :bow:

**Comment by edgarriba** [comment]
cool! you're welcome! :+1:
